#!/usr/bin/env python3
"""Generate the file://-safe Catalog projection of component relation routes.

The production routing manifest remains the source of truth.  Catalog cards only
consume this generated projection, so a label cannot silently drift from the
component that will actually be selected at render time.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "references" / "catalog.html"
ROUTING = ROOT / "capabilities" / "components" / "routing-manifest.json"
OUTPUT = ROOT / "references" / "component-routing-data.js"


def catalog_specs(source: str) -> list[str]:
    match = re.search(
        r"const SMARTART_COMPONENTS=\[(.*?)\n\];\n\n/\* 分类闭合",
        source,
        re.S,
    )
    if not match:
        raise AssertionError("未找到 SMARTART_COMPONENTS")
    block = match.group(1)
    specs = []
    for kind, number, echarts_id in re.findall(
        r"\{t:'(atlas|native|ec)'(?:,num:(\d+)|,id:'([^']+)')", block
    ):
        specs.append(f"{kind}:{echarts_id or number}")
    specs.extend(
        f"{kind}:{key}"
        for kind, key in re.findall(r"\['(atlas|native|ec):([^']+)'", block)
    )
    return sorted(set(specs))


def route_for_spec(spec: str, components: list[dict]) -> dict:
    kind, key = spec.split(":", 1)
    if kind == "ec":
        matches = [item for item in components if item["component_id"] == key]
    elif kind == "atlas":
        prefix = f"atlas.{int(key):03d}."
        matches = [item for item in components if item["component_id"].startswith(prefix)]
    elif kind == "native":
        prefix = f"native.paper-ink.{int(key):03d}."
        matches = [item for item in components if item["component_id"].startswith(prefix)]
    else:
        raise AssertionError(f"未知 Catalog spec: {spec}")
    if len(matches) != 1:
        raise AssertionError(f"{spec} 应唯一映射生产路由，当前 {len(matches)} 个")
    return matches[0]


def build_payload(catalog: str, manifest: dict) -> dict:
    vocabulary = manifest.get("relation_key_vocabulary") or {}
    specs = {}
    for spec in catalog_specs(catalog):
        route = route_for_spec(spec, manifest["components"])
        keys = route.get("relation_keys") or []
        invalid = [key for key in keys if key not in vocabulary]
        if invalid:
            raise AssertionError(f"{route['component_id']} 含词表外关系键: {invalid}")
        if not keys:
            raise AssertionError(f"{route['component_id']} 缺 relation_keys")
        specs[spec] = {
            "component_id": route["component_id"],
            "relation_keys": keys,
        }
    return {
        "contract_version": 1,
        "source": "capabilities/components/routing-manifest.json",
        "vocabulary": vocabulary,
        "specs": specs,
    }


def render(payload: dict) -> str:
    body = json.dumps(payload, ensure_ascii=False, indent=2)
    return (
        "/* Generated by scripts/build_component_routing_data.py; do not edit. */\n"
        f"window.WISE_PPT_COMPONENT_ROUTING = Object.freeze({body});\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="只读验证生成物")
    args = parser.parse_args()

    catalog = CATALOG.read_text(encoding="utf-8")
    manifest = json.loads(ROUTING.read_text(encoding="utf-8"))
    expected = render(build_payload(catalog, manifest))
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            raise AssertionError("component-routing-data.js 不是当前路由清单的确定性投影")
    else:
        OUTPUT.write_text(expected, encoding="utf-8")
    print(
        f"OK: {len(catalog_specs(catalog))} 个 Catalog spec 的关系标签由生产路由清单生成。"
    )


if __name__ == "__main__":
    main()
